name: "NixOS Installation (alderlake)"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        large-packages: false
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-24.05
    - name: Configure nix-daemon
      run: |
        cp /etc/nix/nix.conf nix.conf
        echo 'system-features = benchmark big-parallel kvm nixos-test uid-range gccarch-alderlake' |
          tee -a nix.conf
        sudo rm /etc/nix/nix.conf
        sudo mv nix.conf /etc/nix/nix.conf
        sudo systemctl restart nix-daemon.service
        chmod o+rx /home/runner
    - name: Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v7
    - uses: cachix/cachix-action@v14
      with:
        name: barrbrain-alderlake
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build NixOS
      run: |
        nix-build --extra-substituters 'auto?trusted=1' '<nixpkgs/firefox>' -j 1 \
          -k -A system -I nixos-config="$PWD/rootfs/etc/nixos/configuration.nix"
