name: "NixOS Installation (alderlake)"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: cat /proc/cpuinfo
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        large-packages: false
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-24.05
    - name: Configure nix-daemon
      run: |
        cp /etc/nix/nix.conf nix.conf
        echo 'system-features = benchmark big-parallel kvm nixos-test uid-range gccarch-x86-64-v3' |
          tee -a nix.conf
        sudo rm /etc/nix/nix.conf
        sudo mv nix.conf /etc/nix/nix.conf
        sudo systemctl restart nix-daemon.service
        chmod o+rx /home/runner
    - name: Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v7
    - uses: cachix/cachix-action@v14
      with:
        name: barrbrain-alderlake
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        cachixArgs: '-j8 -c16'
    - name: Build NixOS
      run: |
        nix-build --extra-substituters 'auto?trusted=1' '<nixpkgs/nixos>' \
          -A system -I nixos-config="$PWD/rootfs/etc/nixos/configuration.nix" \
          --dry-run 2>&1 | tee unfree.log
        sed -i '/UNFREE/d' rootfs/etc/nixos/configuration.nix
        nix-build --extra-substituters 'auto?trusted=1' '<nixpkgs/nixos>' \
          -A system -I nixos-config="$PWD/rootfs/etc/nixos/configuration.nix" \
          --dry-run 2>&1 | tee free.log
        echo 'Common derivations:'
        grep -xFf unfree.log free.log | grep '/nix/store' | tr -d ' ' | tee common.log
    - name: Build NixOS
      run: |
          nix-build --extra-substituters 'auto?trusted=1' -j 1 -k -A system \
          -I nixos-config="$PWD/rootfs/etc/nixos/configuration.nix" `grep '\.drv$' common.log`
