name: "NixOS patches"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: git fetch --depth=1 origin nixos-25.05-base
      uses: actions/checkout@v4
      with:
        path: 'nixpkgs'
        repository: 'barrbrain/nixpkgs'
        ref: 'refs/heads/nixos-25.05-base'
    - name: git fetch --depth=1 upstream nixos-25.05
      working-directory: ./nixpkgs
      run: |
        git fetch --depth=1 https://github.com/NixOS/nixpkgs nixos-25.05
        git checkout -B nixos-25.05-base FETCH_HEAD
    - name: Check for new commits
      working-directory: ./nixpkgs
      run: |
        [ `git rev-parse HEAD` != `git rev-parse origin/nixos-25.05-base` ]
    - run: git -C nixpkgs fetch origin nixos-25.05
    - name: Rebase patches
      env:
        GIT_COMMITTER_NAME: David Michael Barr
        GIT_COMMITTER_EMAIL: b@rr-dav.id.au
      working-directory: ./nixpkgs
      run: |
        git checkout -B nixos-25.05
        git cherry-pick --empty=drop origin/nixos-25.05-base..origin/nixos-25.05
    - run: git -C nixpkgs log --pretty=fuller
    - name: Upload new patches
      working-directory: ./nixpkgs
      run: |
        git config --local --unset-all 'http.https://github.com/.extraheader'
        git config --local 'http.https://github.com/.extraheader' \
          'Authorization: Basic ${{ secrets.NIXPKGS_REPO_TOKEN }}'
        git push origin +nixos-25.05-base +nixos-25.05
